local d = (import 'github.com/jsonnet-libs/docsonnet/doc-util/main.libsonnet');
{
  '#':: d.pkg(name='null', url='', help='The `null` package contains functions and utilities for setting up the provider, resources, and data\nsources of the [null Terraform provider](TODO) using Jsonnet.\n\nThis package is autogenerated from the [tf-libsonnet/libgenerator](https://github.com/tf-libsonnet/libgenerator)\nproject.\n'),
  provider: (import 'provider_null.libsonnet'),
  resource: (import 'resources/resource.libsonnet'),
  data: (import 'data/main.libsonnet'),
}
